"""add profile photo_consent

Revision ID: 1c9dd438d03a
Revises: 286b4a2ca936
Create Date: 2026-08-18 20:22:12.194041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9dd438d03a'
down_revision: Union[str, None] = '286b4a2ca936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('photo_consent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'photo_consent')
    # ### end Alembic commands ###
