"""meal photo_url and item is_ai_detected

Revision ID: 25f6503662e8
Revises: 1c9dd438d03a
Create Date: 2026-08-18 21:01:57.583315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f6503662e8'
down_revision: Union[str, None] = '1c9dd438d03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_item', sa.Column('is_ai_detected', sa.Boolean(), nullable=False))
    op.add_column('meal_log', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_log', 'photo_url')
    op.drop_column('meal_item', 'is_ai_detected')
    # ### end Alembic commands ###
