"""init

Revision ID: 286b4a2ca936
Revises: 
Create Date: 2026-08-18 19:59:55.203306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286b4a2ca936'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('MFDS', 'USER_ADDED', name='food_source'), nullable=False),
    sa.Column('serving_g', sa.Integer(), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('sugar_g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('sat_fat_g', sa.Float(), nullable=True),
    sa.Column('omega3_mg', sa.Float(), nullable=True),
    sa.Column('vit_a_ug', sa.Float(), nullable=True),
    sa.Column('vit_c_mg', sa.Float(), nullable=True),
    sa.Column('vit_e_mg', sa.Float(), nullable=True),
    sa.Column('zinc_mg', sa.Float(), nullable=True),
    sa.Column('is_dairy', sa.Boolean(), nullable=False),
    sa.Column('is_high_gi', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_nutrient', sa.String(length=20), nullable=False),
    sa.Column('purpose_tag', sa.String(length=100), nullable=False),
    sa.Column('search_keyword', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('price_band', sa.Enum('LOW', 'MID', 'HIGH', name='price_band'), nullable=True),
    sa.Column('appeal_note', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_key_nutrient'), 'ingredient', ['key_nutrient'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('skin_type', sa.Enum('OILY', 'DRY', 'COMBINATION', name='skin_type'), nullable=True),
    sa.Column('concerns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='meal_type'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cooking_time_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.String(length=30), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('skin_benefits', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skin_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trouble_level', sa.Integer(), nullable=False),
    sa.Column('oil_level', sa.Integer(), nullable=False),
    sa.Column('dryness_level', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('memo', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('ALLERGY', 'DISLIKE', name='constraint_type'), nullable=False),
    sa.Column('ingredient_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_log_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('portion_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['meal_log_id'], ['meal_log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_item')
    op.drop_table('user_constraint')
    op.drop_table('skin_log')
    op.drop_table('recipe')
    op.drop_table('meal_log')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_ingredient_key_nutrient'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_table('food')
    # ### end Alembic commands ###
